Laravel_2 /leBonCoin/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Ligue1Controller;
use App\Http\Controllers\LigaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome.index');
// Route for french championship
Route::resource('/ligue1', 'Ligue1Controller');

// Route for spanish chmpionship

Route::resource('/liga', 'LigaController');

// Route for England championship
Route::resource('/premiereleague', 'PremierController');

//Route for deutcheland championship
Route::resource('/bundesliga', 'BundesligaController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Laravel_2 /leBonCoin/app/Http/Controllers/PremierController.php
<?php

namespace App\Http\Controllers;

use App\Premierleague;
use Illuminate\Http\Request;

class PremierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $premiereleagues = PremierLeague::all();
        return view('/Premier/league', compact('premiereleagues'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('/Premier/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'equipe_anglaise' => 'required',
            'jouer' => 'required',
            'gagner' => 'required',
            'perdu' => 'required',
            'butpour' => 'required',
            'butcontre' => 'required',
            'point' => 'required'
        ]);
        $premiereleague = new Premierleague();
        if ($premiereleague != null) {
            $premiereleague->equipe_anglaise = request('equipe_anglaise');
            $premiereleague->jouer = request('jouer');
            $premiereleague->gagner = request('gagner');
            $premiereleague->perdu = request('perdu');
            $premiereleague->butpour = request('butpour');
            $premiereleague->butcontre = request('butcontre');
            $premiereleague->point = request('point');
            $premiereleague->save();
            return redirect()->route('premiereleague.index')->with('success', 'Votre équipe a été ajouté');
        }
        return view('/Premier/error');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $premiereleague = Premierleague::find($id);
        return view('/Premier/edit', compact('premiereleague'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'equipe_anglaise' => 'required',
            'jouer' => 'required',
            'gagner' => 'required',
            'perdu' => 'required',
            'butpour' => 'required',
            'butcontre' => 'required',
            'point' => 'required'
        ]);
        $premiereleague = Premierleague::find($id);
        if ($premiereleague != null) {
            $premiereleague->equipe_anglaise = request('equipe_anglaise');
            $premiereleague->jouer = request('jouer');
            $premiereleague->gagner = request('gagner');
            $premiereleague->perdu = request('perdu');
            $premiereleague->butpour = request('butpour');
            $premiereleague->butcontre = request('butcontre');
            $premiereleague->point = request('point');
            $premiereleague->save();
            return redirect()->route('premiereleague.index')->with('modifier', 'l\'équipe a été modifier');
        }
        return view('/Premier/error');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $premiereleague = Premierleague::find($id);
        if ($premiereleague != null) {
            $premiereleague->delete($id);
            return redirect()->route('premiereleague.index')->with('supprimer', 'l\'équipe a été supprimer');
        }
        return view('/Premier/error');
    }
}

Laravel_2 /leBonCoin/resources/views/Premier/create.blade.php
@extends('welcome')
@section('content')
<div class="creat">
    <h3> Veuillez ajouter une équipe</h3>
<form action="{{ route('premiereleague.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Nom équipe</label>
        <input type="text" name="equipe_anglaise" class="form-control" placeholder="Taper le nom de l'équipe">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match jouer</label>
        <input type="text" name="jouer" class="form-control" placeholder="mettez un nombre">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match gagner</label>
        <input type="text" name="gagner" class="form-control" placeholder="mettez un nombre">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match perdu</label>
        <input type="text" name="perdu" class="form-control" placeholder="mettez un nombre">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">But pour</label>
        <input type="text" name="butpour" class="form-control" placeholder="mettez un nombre">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">But contre</label>
        <input type="text" name="butcontre" class="form-control" placeholder="mettez un nombre">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Point</label>
        <input type="text" name="point" class="form-control" placeholder="mettez un nombre">
    </div>
    <button type="submit" class="btn btn-success">ajouter</button>
</form>
</div>
@endsection

Laravel_2 /leBonCoin/resources/views/Premier/edit.blade.php
@extends('welcome')
@section('content')
<div class="edition">
    <h3> Veuillez Modifier votre équipe</h3>
<form action="{{ route('premiereleague.update', ['premiereleague'=>$premiereleague])}}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Nom équipe</label>
        <input type="text" name="equipe_anglaise" class="form-control"  placeholder="Modifier votre equipe" value="{{ $premiereleague->equipe_anglaise}}">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match jouer</label>
        <input type="text" name="jouer" class="form-control" value="{{ $premiereleague->jouer}}" placeholder="Modifier les matchs jouer">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match gagner</label>
        <input type="text" name="gagner" class="form-control" value="{{ $premiereleague->gagner}}" placeholder="Modifier les matchs gagner">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match perdu</label>
        <input type="text" name="perdu" class="form-control" value="{{ $premiereleague->perdu}}" placeholder="Modifier les matchs perdu">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">But pour</label>
        <input type="text" name="butpour" class="form-control" value="{{ $premiereleague->butpour}}" placeholder="Modifier modifier les buts pour">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">But contre</label>
        <input type="text" name="butcontre" class="form-control" value="{{ $premiereleague->butcontre}}" placeholder="Modifier les buts contre ">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Point</label>
        <input type="text" name="point" class="form-control" value="{{ $premiereleague->point}}" placeholder="Modifier les points ">
    </div>
    <button type="submit" class="btn btn-success boutton">Modifier</button>
</form>
</div>
@endsection

Laravel_2 /leBonCoin/resources/views/Premier/error.blade.php
@extends('welcome')
@section('content')
    <h2>Désoler une erreur s'est produite refaite l'operation</h2>
@endsection
    

Laravel_2 /leBonCoin/resources/views/Premier/league.blade.php
   @extends('welcome')
   @section('content')
   <div class="container">
        <h2> Championnat Anglais</h2>
           <a href="{{route('premiereleague.create')}}" class="btn btn-success"> Ajouter une équipe</a>
               <table class="table table-hover">
                   <thead>
                       <tr>
                           <th scope="col">classement</th>
                           <th scope="col">équipe</th>
                           <th scope="col">MJ</th>
                           <th scope="col">MG</th>
                           <th scope="col">MP</th>
                           <th scope="col">BP</th>
                           <th scope="col">BC</th>
                           <th scope="col">Point</th>
                           <th scope="col">Action</th>
                       </tr>
                   </thead>
                       @foreach ($premiereleagues as $premiereleague)
                           <tr>
                               <th>{{$premiereleague->id}}</th>
                               <td>{{$premiereleague->equipe_anglaise}}</td>
                               <td>{{$premiereleague->jouer}}</td>
                               <td>{{$premiereleague->gagner}}</td>
                               <td>{{$premiereleague->perdu}}</td>
                               <td>{{$premiereleague->butpour}}</td>
                               <td>{{$premiereleague->butcontre}}</td>
                               <td>{{$premiereleague->point}}</td>
                               <td class="action">
                                  
                                    <a href="{{ route('premiereleague.edit',['premiereleague'=>$premiereleague])}}" class="btn btn-warning">Modifier</a> 
                                   <a> 
                                      <form action="{{ route('premiereleague.destroy',['premiereleague'=>$premiereleague])}}"
                                            method="POST" enctype="multipart/form-data"
                                            onsubmit="return confirm('Voulez Vous vraiment supprimer ce magasin')" >
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger">Supprimer </button>
                                       </form>
                                    </a>  
                               </td>     
                           </tr>
                       @endforeach
                      
               </table>
   </div>            
   @endsection
   