Laravel_2 /leBonCoin/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Ligue1Controller;
use App\Http\Controllers\LigaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome.index');
// Route for french championship
Route::resource('/ligue1', 'Ligue1Controller');

// Route for spanish chmpionship

Route::resource('/liga', 'LigaController');

// Route for England championship
Route::resource('/premiereleague', 'PremierController');

//Route for deutcheland championship
Route::resource('/bundesliga', 'BundesligaController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Laravel_2 /leBonCoin/app/Liga.php
<?php

namespace App;

use App\Http\Controllers\LigaController;

use Illuminate\Database\Eloquent\Model;

class Liga extends Model
{
    protected $fillable = ['id', 'equipe', 'jouer', 'gagner', 'perdu', 'butpour', 'butcontre', 'point'];
}

Laravel_2 /leBonCoin/app/Http/Controllers/LigaController.php
<?php

namespace App\Http\Controllers;

use App\Liga;
use Illuminate\Http\Request;

class LigaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ligas = Liga::all();
        return view('/Liga/liga', compact('ligas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('/Liga/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Liga $liga)
    {
        // validation before registration
        $request->validate([
            'equipe' => 'required',
            'jouer' => 'required',
            'gagner' => 'required',
            'perdu' => 'required',
            'butpour' => 'required',
            'butcontre' => 'required',
            'point' => 'required',
        ]);
        $liga = new Liga();
        if ($liga != null) {
            $liga->equipe = request('equipe');
            $liga->jouer = request('jouer');
            $liga->gagner = request('gagner');
            $liga->perdu = request('perdu');
            $liga->butpour = request('butpour');
            $liga->butcontre = request('butcontre');
            $liga->point = request('point');
            $liga->save();
            return redirect()->route('liga.index')->with('success', 'votre équipe a été ajouté');
        }
        return view('/Liga/error');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $liga = Liga::find($id);
        return view('Liga/edit', compact('liga'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'equipe' => 'required',
            'jouer' => 'required',
            'gagner' => 'required',
            'perdu' => 'required',
            'butpour' => 'required',
            'butcontre' => 'required',
            'point' => 'required',
        ]);
        $liga = Liga::find($id);
        if ($liga != null) {
            $liga->equipe = request('equipe');
            $liga->jouer = request('jouer');
            $liga->gagner = request('gagner');
            $liga->perdu = request('perdu');
            $liga->butpour = request('butpour');
            $liga->butcontre = request('butcontre');
            $liga->point = request('point');
            $liga->save();
            return redirect()->route('liga.index')->with('modifier', 'Votre équipe a été modifier');
        }
        return view('/Liga/error');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $liga = Liga::find($id);
        if ($liga != null) {
            $liga->delete();
            return redirect()->route('liga.index')->with('supprimer', 'Votre équipe a été supprimer');
        }
        return view('/Liga/error');
    }
}

Laravel_2 /leBonCoin/resources/views/Liga/create.blade.php
@extends('welcome')
@section('content')
<div class="creat">
    <h3> Veuillez ajouter une équipe</h3>
<form action="{{ route('liga.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Nom équipe</label>
        <input type="text" name="equipe" class="form-control" placeholder="Taper le nom de l'équipe">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match jouer</label>
        <input type="text" name="jouer" class="form-control" placeholder="mettez un nombre">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match gagner</label>
        <input type="text" name="gagner" class="form-control" placeholder="mettez un nombre">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match perdu</label>
        <input type="text" name="perdu" class="form-control" placeholder="mettez un nombre">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">But pour</label>
        <input type="text" name="butpour" class="form-control" placeholder="mettez un nombre">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">But contre</label>
        <input type="text" name="butcontre" class="form-control" placeholder="mettez un nombre">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Point</label>
        <input type="text" name="point" class="form-control" placeholder="mettez un nombre">
    </div>
    <button type="submit" class="btn btn-success">ajouter</button>
</form>
</div>
@endsection

Laravel_2 /leBonCoin/resources/views/Liga/edit.blade.php
@extends('welcome')
@section('content')
<div class="edition">
    <h3>Veuillez modifier votre équipe</h3>
<form action="{{ route('liga.update',['liga'=>$liga]) }}"
    method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Nom équipe</label>
        <input type="text" name="equipe" class="form-control" value="{{ $liga->equipe }}">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match jouer</label>
        <input type="text" name="jouer" class="form-control" value="{{ $liga->jouer }}">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match gagner</label>
        <input type="text" name="gagner" class="form-control" value="{{ $liga->gagner }}">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Match perdu</label>
        <input type="text" name="perdu" class="form-control" value="{{ $liga->perdu }}">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">But pour</label>
        <input type="text" name="butpour" class="form-control" value="{{ $liga->butpour }}">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">But contre</label>
        <input type="text" name="butcontre" class="form-control" value="{{ $liga->butcontre }}">
    </div>
    <div class="mb-3 form group">
        <label for="exampleFormControlInput1" class="form-label">Point</label>
        <input type="text" name="point" class="form-control" value="{{ $liga->point }}">
    </div>
    <button type="submit" class="btn btn-success boutton">Modfier</button>
</form>
</div>
@endsection

Laravel_2 /leBonCoin/resources/views/Liga/error.blade.php
@extends('welcome')
@section('content')
    <h2>Désoler une erreur s'est produite refaite l'operation</h2>
@endsection

Laravel_2 /leBonCoin/resources/views/Liga/liga.blade.php
@extends('welcome')
@section('content')
<div class="container">
<h2> Classement Championnat espagnole</h2>
<a href="{{ route('liga.create') }}" class="btn btn-success">ajouter une equipe</a>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">classement</th>
            <th scope="col">equipe</th>
            <th scope="col">MJ</th>
            <th scope="col">MG</th>
            <th scope="col">MP</th>
            <th scope="col">BP</th>
            <th scope="col">BC</th>
            <th scope="col">Point</th>
            <th>Action</th>
        </tr>
    </thead>
    @foreach($ligas as $liga)
        <tbody class="col">

            <tr>
                <th scope="col">{{ $liga->id }}</th>
                <td scope="col">{{ $liga->equipe }}</td>
                <td scope="col">{{ $liga->jouer }}</td>
                <td scope="col">{{ $liga->gagner }}</td>
                <td scope="col">{{ $liga->perdu }}</td>
                <td scope="col">{{ $liga->butpour }}</td>
                <td scope="col">{{ $liga->butcontre }}</td>
                <td scope="col">{{ $liga->point }}</td>
                <td class="action"> <a
                        href="{{ route('liga.edit',['liga'=>$liga]) }}"
                        class="btn btn-warning"> Modifier </a>
                    <a>
                        <form
                            action="{{ route('liga.destroy',['liga'=>$liga]) }}"
                            method="POST" enctype="multipart/form-data"
                            onsubmit="return confirm('Voulez Vous vraiment supprimer ce magasin')" ;>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Supprimer</button>
                        </form>
                    </a>
                </td>
            </tr>
        </tbody>
    @endforeach
</table>
</div>
@endsection